version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app
    container_name: node-app
    env_file: .env
    ports:
      - "3000:3000"
  redis:
    image: redis:latest   
    container_name: redis-store
